module.exports = [
	'Miami Beach,FL',
	'San Francisco,CA',
	'Santa Monica,CA',
	'Los Angeles,CA',
	'Seattle,WA',
	'Orlando,FL',
	'Tampa,FL',
	'San Jose,CA',
	'San Diego,CA',
	'Santa Ana,CA',
	'Denver,CO',
	'Phoenix,AZ',
	'Salt Lake City,UT',
	'Chicago,IL',
	'Philadelphia,PA',
	'Dallas,TX',
	'Houston,TX',
	'Nashville,TN',
	'New York City,NY',
	'San Antonio,TX',
	'Austin,TX',
	'Jacksonville,FL',
	'Indianapolis,IN',
	'Columbus,OH',
	'Fort Worth,TX',
	'Charlotte,NC',
	'El Paso,TX',
	'Detroit,MI',
	'Washington,DC',
	'Boston,MA',
	'Memphis,TN',
	'Nashville,TN',
	'Portland,OR',
	'Oklahoma City,OK',
	'Las Vegas,NV',
	'Baltimore,MD',
	'Louisville,KY',
	'Milwaukee,WI',
	'Albuquerque,NM',
	'Tucson,AZ',
	'Fresno,CA',
	'Sacramento,CA',
	'Kansas City,MO',
	'Long Beach,CA',
	'Mesa,AZ',
	'Atlanta,GA',
	'Colorado Springs,CO',
	'Virginia Beach,VA',
	'Raleigh,NC',
	'Omaha,NE',
	'Miami,FL',
	'Oakland,CA',
	'Minneapolis,MN',
	'Tulsa,OK',
	'Wichita,KS',
	'New Orleans,LA',
	'Arlington,TX'
];
